# Site settings
title: Salebarn
email: MarkBruns@MarkBruns.com
description: Accelerate the negotiation! The SALEBARN project is about improving the quality, speed and general execution of those important, recurrent tasks that are associated with selling something or developing new business.
twitter_username: Salebarn_LLC
github_username:  Salebarn

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine