# Site settings
title: Melon Cave
email: MarkBruns@MarkBruns.com
description: Cave in the melon of zombie couch mashed-potatoness. KNOCK OFF the BAD HABITS of being yourself.
twitter_username: MarkBruns
github_username:  MelonCave

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
