# Site settings
title: Melon Cave
email: MarkBruns@MarkBruns.com
description: KNOCK OFF the BAD HABITS of being yourself. Stop fucking yourself over. Don't negotiate with your demons. Cave in your bad habit melon.
twitter_username: MarkBruns
github_username:  MelonCave

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
