# Site settings
title: Melon Cave
email: MarkBruns@MarkBruns.com
description: KNOCK OFF the BAD HABITS of being yourself. Get serious about caving in your bad habit melon.
twitter_username: MarkBruns
github_username:  MelonCave

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
