# Site settings
title: Salebarn
email: salebarn@gmail.com
description: Accelerating negotiations ... increasing the bid, building momentum, friendraising to improve the health of communities.
twitter_username: Salebarn_LLC
github_username:  Salebarn

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
