# Site settings
title: Salebarn
email: salebarn@gmail.com
description: The SALEBARN project is focused upon accelerating NEW business. development.
twitter_username: Salebarn_LLC
github_username:  Salebarn

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
