# Site settings
title: Salebarn
email: salebarn@gmail.com
description: SALEBARN focuses upon accelerating negotiations. The SECRET SAUCE of social media is the USER. Social media biz gets it wrong thinking USER data is the product.
twitter_username: Salebarn_LLC
github_username:  Salebarn

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
