# Site settings
title: Salebarn
email: MarkBruns@MarkBruns.com
description: The SALEBARN project is accelerating and improving the execution of those recurrent tasks that are associated with selling something or developing new business.
twitter_username: Salebarn_LLC
github_username:  Salebarn

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine